name: Remote Deploy

on:
  push:
    branches:
      - master
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure SSH Connection
        run : |
          mkdir -p ~/.ssh/
          echo "$BIT_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
      - name: Clean Repo
        run: |
          rm -rf ./.github
          git rm -r --cached ./.github
          [ -e ./auth.json ] && git rm -r --cached ./auth.json
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_USERNAME"
          git add .
          git status
          git commit -m "Trigger Build" --allow-empty
      - name: Rewrite History
        run: |
          git remote add remote $REMOTE_REPO_SSH
          git filter-branch -f --env-filter "
              GIT_AUTHOR_NAME='$GIT_AUTHOR_USERNAME'
              GIT_AUTHOR_EMAIL='$GIT_AUTHOR_EMAIL'
              GIT_COMMITTER_NAME='$GIT_AUTHOR_USERNAME'
              GIT_COMMITTER_EMAIL='$GIT_AUTHOR_EMAIL'
            " HEAD
      - name: Push to remote
        run: |
          git push -f remote master
env:
  BIT_KEY: ${{ secrets.BIT_KEY }} #It uses the NON pub key
  REMOTE_REPO_SSH: ${{ secrets.REMOTE_REPO_SSH }}
  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  GIT_AUTHOR_USERNAME: ${{ secrets.GIT_AUTHOR_USERNAME }}